### ISSUE TITLE
Finish first page

### ISSUE THREAD

**Issue by RichStone** [Jf-lagos/product-page#1]
- [x] let's rename the repository to product-page (no need to have uppercase letters in repo names ;)
- [x] add a .gitignore and ignore all files that don't below into the repository
- [x] let's be more neutral and rename the `photos` directory to `images` (maybe some pictures will not be photos but still images if you know what I mean :grimacing:)
- [x] with the new images of the smartwatches, let's also having a naming convention of `smartwatch-1.png` (lowercase and dashed)
- [x] I like the cards in front and in background but let's remove the borders and add some shadow instead (as if sun would shine on the cards from uppper left for example :sun_with_face: :D let me know if you know what I mean :))

A few more additions to make this first page ready:

- [x] add soft font to "Add cart" 
- [x] add a description
- [x] let's make a subtle transition if someone hovers on the button so that the button becomes like 10%-20% bigger

If you like, we can work with branches and PRs from now on inside this repositories for bigger fixes.

Really cool so far I'm sure we can work with that: The HTML and JS are simple and readable :rocket: Also good idea to get early feedback from me on that before continuing.

**Comment by Jf-lagos** [comment]
Hi Rich thanks for your feedback

Can you please explain to me what do mean by "working in branch" ? I don't really know when do I need to create a new branch. 
For instance, when I added the box-shadow, did I need  to create a new branch for that ? 
Also, what's the point of PRs ? 

Thanks for your help, as I'm not really familiar with these GitHub features.

**Comment by RichStone** [comment]
Sure, these are super important concepts in collaboration and how code gets merged from being just a feature on someone's local computer to be "in production" where users see it. Let's discuss it later in more detail, but great work so far :))
